# Generated by Django 5.2.12 on 2026-09-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantitty',
        ),
        migrations.AddField(
            model_name='product',
            name='body_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('wagon', 'Wagon'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('van', 'Van'), ('pickup', 'Pickup')], db_index=True, default='sedan', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(db_index=True, default='Unknown', max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='used', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='drive_type',
            field=models.CharField(blank=True, choices=[('fwd', 'Front-wheel drive'), ('rwd', 'Rear-wheel drive'), ('awd', 'All-wheel drive')], max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='engine_volume',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], db_index=True, default='petrol', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='horsepower',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(db_index=True, default='Unknown', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='mileage',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Mileage in kilometres'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_name',
            field=models.CharField(db_index=True, default='Unknown', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='automatic', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.PositiveIntegerField(db_index=True, default=2000),
        ),
    ]
