# Generated by Django 5.2.12 on 2026-09-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_quantitty_product_body_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
    ]
