# Generated by Django 6.0.6 on 2026-06-11 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default='user_photo/default.jpg', null=True, upload_to='user_photo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.jpg', '.png', '.jpeg'])]),
        ),
    ]
