# Generated by Django 6.0.6 on 2026-06-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='user_photo/default.jpg', null=True, upload_to='user_photo/'),
        ),
    ]
