# Generated by Django 5.2.12 on 2026-09-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
        ('product', '0003_product_currency'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='carditem',
            constraint=models.UniqueConstraint(fields=('card', 'product'), name='unique_card_product'),
        ),
    ]
