import { createContext, useContext, useEffect, useState } from 'react'
import { BrowserRouter, Link, Navigate, Route, Routes, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { ArrowRight, CarFront, ChevronLeft, ChevronRight, CircleUserRound, Heart, LogOut, Menu, Search, SlidersHorizontal, UserRound, X } from 'lucide-react'
import api, { API_URL } from './api'
import './App.css'

const AuthContext = createContext(null)
const CompareContext = createContext(null)

function message(error) {
  const data = error.response?.data
  if (typeof data === 'string') return data
  if (data?.msg || data?.detail || data?.error) return data.msg || data.detail || data.error
  const firstError = Object.values(data || {})[0]
  return Array.isArray(firstError) ? firstError[0] : firstError || 'Something went wrong. Please try again.'
}

function imageUrl(image) {
  if (!image) return null
  return image.startsWith('http') ? image : `${API_URL}${image.startsWith('/') ? '' : '/'}${image}`
}

const FALLBACK_CAR_IMAGES = {
  sedan: 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=1200&q=85',
  suv: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=85',
  coupe: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=85',
  hatchback: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=85',
  wagon: 'https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=1200&q=85',
  convertible: 'https://images.unsplash.com/photo-1504215680853-026ed2a45def?auto=format&fit=crop&w=1200&q=85',
  pickup: 'https://images.unsplash.com/photo-1551830820-330a71b99659?auto=format&fit=crop&w=1200&q=85',
  van: 'https://images.unsplash.com/photo-1562141961-b9d17c16c8f6?auto=format&fit=crop&w=1200&q=85',
}

function carImage(car, image) {
  return imageUrl(image) || FALLBACK_CAR_IMAGES[car.body_type] || FALLBACK_CAR_IMAGES.suv
}

function useAuth() { return useContext(AuthContext) }
function useCompare() { return useContext(CompareContext) }

function AuthProvider({ children }) {
  const [user, setUser] = useState(null)
  const [loading, setLoading] = useState(Boolean(localStorage.getItem('access')))
  useEffect(() => {
    if (!localStorage.getItem('access')) return setLoading(false)
    api.get('/auth/profile').then(({ data }) => setUser(data)).catch(() => setUser(null)).finally(() => setLoading(false))
  }, [])
  const login = async (form) => {
    const { data } = await api.post('/auth/login', form)
    localStorage.setItem('access', data.access)
    localStorage.setItem('refresh', data.refresh)
    const profile = await api.get('/auth/profile')
    setUser(profile.data)
  }
  const logout = async () => {
    try { await api.post('/auth/logout/', { refresh: localStorage.getItem('refresh') }) } catch { /* token may already be expired */ }
    localStorage.removeItem('access'); localStorage.removeItem('refresh'); setUser(null)
  }
  return <AuthContext.Provider value={{ user, setUser, login, logout, loading }}>{children}</AuthContext.Provider>
}

function CompareProvider({ children }) {
  const [ids, setIds] = useState(() => JSON.parse(localStorage.getItem('motive_compare') || '[]'))
  useEffect(() => localStorage.setItem('motive_compare', JSON.stringify(ids)), [ids])
  const toggle = (id) => setIds((current) => current.includes(id) ? current.filter((item) => item !== id) : current.length >= 4 ? current : [...current, id])
  return <CompareContext.Provider value={{ ids, toggle }}>{children}</CompareContext.Provider>
}

function Header() {
  const { user, logout } = useAuth()
  const [open, setOpen] = useState(false)
  return <header className="topbar"><Link className="brand" to="/"><span className="brand-mark"><CarFront size={17} /></span>MOTIVE<span className="brand-dot">.</span></Link><nav><Link to="/cars">Cars</Link><Link to="/categories">Categories</Link><Link to="/compare">Compare</Link><Link to="/favorites">Favorites</Link><Link to="/cart">Cart</Link><Link to="/orders">Orders</Link></nav><div className="header-actions"><Link className="icon-btn" to="/cars" aria-label="Search cars"><Search size={18} /></Link>{user ? <div className="account-menu"><button className="account-button" onClick={() => setOpen(!open)}><CircleUserRound size={19} />{user.username || user.email}<ChevronRight size={14} /></button>{open && <div className="account-popover"><Link to="/profile" onClick={() => setOpen(false)}>Profile</Link><Link to="/favorites" onClick={() => setOpen(false)}>My favorites</Link><Link to="/cart" onClick={() => setOpen(false)}>Cart</Link><Link to="/orders" onClick={() => setOpen(false)}>My orders</Link><button onClick={logout}><LogOut size={15} />Log out</button></div>}</div> : <Link className="profile-link" to="/login"><UserRound size={17} />Sign in</Link>}<button className="icon-btn menu-btn" onClick={() => setOpen(!open)} aria-label="Menu"><Menu size={19} /></button></div></header>
}

function Loading({ label = 'Loading' }) { return <div className="state"><div className="spinner" /><p>{label}...</p></div> }
function ErrorState({ error, retry }) { return <div className="state error-state"><h3>We could not load this view</h3><p>{message(error)}</p>{retry && <button className="secondary-btn" onClick={retry}>Try again</button>}</div> }
function Empty({ title, text }) { return <div className="state"><CarFront size={31} /><h3>{title}</h3><p>{text}</p></div> }

function CarCard({ car, favoriteIds, onFavorite }) {
  const { ids, toggle } = useCompare()
  const image = carImage(car, car.images?.find((item) => item.is_main)?.image || car.images?.[0]?.image)
  const favorite = favoriteIds?.includes(car.id)
  return <article className="car-card"><Link to={`/cars/${car.id}`} className="car-image"><img src={image} loading="lazy" alt={`${car.brand} ${car.model_name}`} onError={(event) => { event.currentTarget.src = FALLBACK_CAR_IMAGES.suv }} /><button className={`save-btn ${favorite ? 'saved' : ''}`} onClick={(event) => { event.preventDefault(); onFavorite?.(car.id) }} aria-label={favorite ? 'Remove favorite' : 'Save car'}><Heart size={17} fill={favorite ? 'currentColor' : 'none'} /></button></Link><div className="car-info"><p className="eyebrow">{car.brand}</p><div className="car-heading"><h3>{car.model_name}</h3><strong>{car.currency || 'EUR'} {Number(car.price).toLocaleString()}</strong></div><div className="car-meta"><span>{car.year}</span><span>{Number(car.mileage).toLocaleString()} km</span><span>{car.transmission}</span></div><p className="location">{car.fuel_type} · {car.body_type} · {car.location}</p><button className={`compare-toggle ${ids.includes(car.id) ? 'active' : ''}`} onClick={() => toggle(car.id)}><SlidersHorizontal size={14} />{ids.includes(car.id) ? 'Compared' : 'Compare'}</button></div></article>
}

function useProducts(params = '') {
  const [state, setState] = useState({ loading: true, data: null, error: null })
  const load = () => { setState({ loading: true, data: null, error: null }); api.get(`/product/${params}`).then(({ data }) => setState({ loading: false, data, error: null })).catch((error) => setState({ loading: false, data: null, error })) }
  useEffect(load, [params])
  return { ...state, retry: load }
}

function useFavorites() {
  const { user } = useAuth(); const [favorites, setFavorites] = useState([]); const [error, setError] = useState(null)
  const load = () => { if (!user) return setFavorites([]); api.get('/comment/saved/').then(({ data }) => setFavorites(data)).catch(setError) }
  useEffect(load, [user])
  const toggle = async (id) => { if (!user) return setError(new Error('Sign in to save cars.')); try { await api.post(`/comment/saved/${id}/`); await load() } catch (requestError) { setError(requestError) } }
  return { favorites, ids: favorites.map((car) => car.id), toggle, error }
}

function Home() {
  const { data, loading, error, retry } = useProducts('?ordering=-created_at&page_size=6'); const [query, setQuery] = useState(''); const navigate = useNavigate(); const favorites = useFavorites()
  const brands = [...new Set((data?.results || []).map((car) => car.brand))].slice(0, 6)
  return <><section className="hero"><div className="hero-copy"><p className="eyebrow accent">MOTIVE / curated inventory</p><h1>Find the car<br /><em>that fits your life.</em></h1><p className="hero-sub">A focused marketplace for considered cars, transparent details, and a calmer way to buy.</p><form className="search-panel" onSubmit={(event) => { event.preventDefault(); navigate(`/cars?search=${encodeURIComponent(query)}`) }}><Search size={19} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search brand, model or keyword" /><button>Search <ArrowRight size={16} /></button></form><div className="trust-row"><span>Verified listings</span><span>Real-time availability</span></div></div><div className="hero-visual"><div className="hero-visual-copy"><span>Drive differently.</span><strong>01</strong></div></div></section><main className="page"><section className="section-head"><div><p className="eyebrow">Latest arrivals</p><h2>Cars worth<br /><em>looking twice at.</em></h2></div><Link className="text-link" to="/cars">View all cars <ArrowRight size={16} /></Link></section>{loading && <Loading label="Loading inventory" />}{error && <ErrorState error={error} retry={retry} />}{data && <div className="car-grid">{(data.results || []).map((car) => <CarCard key={car.id} car={car} favoriteIds={favorites.ids} onFavorite={favorites.toggle} />)}</div>}{data?.results?.length === 0 && <Empty title="No cars listed yet" text="Run the seed_cars command or check back soon." />}<section className="brands"><p className="eyebrow">Explore by marque</p><div className="brand-list">{brands.map((brand) => <Link to={`/cars?brand=${encodeURIComponent(brand)}`} key={brand}>{brand}<ArrowRight size={14} /></Link>)}</div></section></main></>
}

function Catalog() {
  const [searchParams, setSearchParams] = useSearchParams(); const [filters, setFilters] = useState(Object.fromEntries(searchParams.entries())); const query = new URLSearchParams(filters).toString(); const { data, loading, error, retry } = useProducts(query ? `?${query}` : ''); const favorites = useFavorites();
  const update = (key, value) => { const next = { ...filters, [key]: value }; if (!value) delete next[key]; setFilters(next); setSearchParams(next) }
  return <main className="page catalog-page"><div className="catalog-title"><div><p className="eyebrow accent">The inventory</p><h1>Find your next<br /><em>great drive.</em></h1></div><span className="result-count">{data?.count ?? 0} cars</span></div><div className="filter-bar"><label className="filter-search"><Search size={17} /><input value={filters.search || ''} onChange={(event) => update('search', event.target.value)} placeholder="Brand, model or keyword" /></label><select value={filters.body_type || ''} onChange={(event) => update('body_type', event.target.value)}><option value="">Body type</option>{['sedan', 'suv', 'coupe', 'hatchback', 'wagon'].map((item) => <option key={item} value={item}>{item}</option>)}</select><select value={filters.fuel_type || ''} onChange={(event) => update('fuel_type', event.target.value)}><option value="">Fuel</option>{['petrol', 'diesel', 'hybrid', 'electric'].map((item) => <option key={item} value={item}>{item}</option>)}</select><select value={filters.transmission || ''} onChange={(event) => update('transmission', event.target.value)}><option value="">Transmission</option><option value="automatic">Automatic</option><option value="manual">Manual</option></select><select value={filters.ordering || ''} onChange={(event) => update('ordering', event.target.value)}><option value="">Sort</option><option value="-created_at">Newest</option><option value="price">Price: low</option><option value="-price">Price: high</option><option value="-mileage">Lowest mileage</option></select><button className="reset-button" onClick={() => { setFilters({}); setSearchParams({}) }}><X size={15} />Reset</button></div>{loading && <Loading label="Loading inventory" />}{error && <ErrorState error={error} retry={retry} />}{data && !data.results?.length && <Empty title="No cars found" text="Try changing your filters." />}{data && <div className="car-grid">{data.results.map((car) => <CarCard key={car.id} car={car} favoriteIds={favorites.ids} onFavorite={favorites.toggle} />)}</div>}<Pagination data={data} onPage={(page) => update('page', page)} /></main>
}

function Pagination({ data, onPage }) { if (!data || (!data.next && !data.previous)) return null; const nextPage = data.next ? Number(new URL(data.next).searchParams.get('page')) : Number(new URL(data.previous).searchParams.get('page')); const currentPage = data.next ? nextPage - 1 : nextPage + 1; return <div className="pagination"><button disabled={!data.previous} onClick={() => onPage(currentPage - 1)}><ChevronLeft size={16} />Previous</button><span>Page {currentPage}</span><button disabled={!data.next} onClick={() => onPage(currentPage + 1)}>Next<ChevronRight size={16} /></button></div> }

function Detail() {
  const { id } = useParams(); const [state, setState] = useState({ loading: true, error: null, car: null }); const [active, setActive] = useState(0); const favorites = useFavorites(); const { ids, toggle } = useCompare(); const { user } = useAuth(); const navigate = useNavigate()
  useEffect(() => { api.get(`/product/${id}/`).then(({ data }) => setState({ loading: false, car: data.product, error: null })).catch((error) => setState({ loading: false, car: null, error })) }, [id])
  if (state.loading) return <main className="page"><Loading label="Loading car" /></main>
  if (state.error) return <main className="page"><ErrorState error={state.error} /></main>
  const car = state.car; const images = car.images || []; const image = carImage(car, images[active]?.image); const favorite = favorites.ids.includes(car.id)
  const order = async () => { if (!user) return navigate('/login'); try { await api.post('/card/', { product: car.id, count: 1 }); navigate('/cart') } catch (error) { window.alert(message(error)) } }
  return <main className="page detail-page"><Link className="back-link" to="/cars">← Back to inventory</Link><div className="detail-layout"><div><div className="gallery-main"><img src={image} alt={`${car.brand} ${car.model_name}`} onError={(event) => { event.currentTarget.src = FALLBACK_CAR_IMAGES.suv }} /><button className="gallery-arrow prev" disabled={active === 0} onClick={() => setActive(active - 1)} aria-label="Previous image"><ChevronLeft /></button><button className="gallery-arrow next" disabled={active === images.length - 1} onClick={() => setActive(active + 1)} aria-label="Next image"><ChevronRight /></button></div>{images.length > 1 && <div className="thumbs">{images.map((item, index) => <button className={active === index ? 'active' : ''} key={item.id} onClick={() => setActive(index)}><img src={imageUrl(item.image)} alt="" /></button>)}</div>}</div><div className="detail-copy"><p className="eyebrow accent">{car.category?.title || car.body_type} · {car.location}</p><h1>{car.brand}<br /><em>{car.model_name}</em></h1><div className="detail-price">€{Number(car.price).toLocaleString()}</div><div className="spec-grid">{[['Year', car.year], ['Mileage', `${Number(car.mileage).toLocaleString()} km`], ['Fuel', car.fuel_type], ['Gearbox', car.transmission], ['Body', car.body_type], ['Drive', car.drive_type || 'Not listed'], ['Color', car.color || 'Not listed'], ['Condition', car.condition]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><p className="description">{car.desc}</p><div className="detail-actions"><button className="primary-btn" onClick={order}>Add to cart <ArrowRight size={16} /></button><button className={`secondary-btn ${favorite ? 'active' : ''}`} onClick={() => { if (!user) navigate('/login'); else favorites.toggle(car.id) }}><Heart size={16} fill={favorite ? 'currentColor' : 'none'} />{favorite ? 'Saved' : 'Save car'}</button><button className={`secondary-btn ${ids.includes(car.id) ? 'active' : ''}`} onClick={() => toggle(car.id)}><SlidersHorizontal size={16} />{ids.includes(car.id) ? 'Compared' : 'Compare'}</button></div></div></div><Comments productId={car.id} /></main>
}

function Comments({ productId }) { const { user } = useAuth(); const [comments, setComments] = useState([]); const [text, setText] = useState(''); const [rating, setRating] = useState(5); const load = () => api.get(`/comment/product/${productId}/`).then(({ data }) => setComments(data)).catch(() => {}); useEffect(load, [productId]); const submit = async (event) => { event.preventDefault(); if (!user) return; await api.post(`/comment/product/${productId}/`, { text, rating }); setText(''); load() }; return <section className="comments"><div className="section-head"><div><p className="eyebrow">Owner notes</p><h2>What people<br /><em>noticed.</em></h2></div></div>{comments.map((comment) => <article className="comment" key={comment.id}><strong>{comment.username}</strong><span>{'★'.repeat(comment.rating)}</span><p>{comment.text}</p></article>)}{user && <form className="comment-form" onSubmit={submit}><textarea value={text} onChange={(event) => setText(event.target.value)} placeholder="Share a considered note" required /><div><select value={rating} onChange={(event) => setRating(event.target.value)}>{[5, 4, 3, 2, 1].map((value) => <option key={value} value={value}>{value} stars</option>)}</select><button className="secondary-btn">Add review</button></div></form>}</section> }

function Categories() { const [state, setState] = useState({ loading: true, data: [], error: null }); useEffect(() => { api.get('/category/').then(({ data }) => setState({ loading: false, data, error: null })).catch((error) => setState({ loading: false, data: [], error })) }, []); if (state.loading) return <main className="page"><Loading label="Loading categories" /></main>; return <main className="page"><p className="eyebrow accent">Browse by shape</p><h1 className="page-title">Find your<br /><em>next silhouette.</em></h1>{state.error ? <ErrorState error={state.error} /> : <div className="category-grid">{state.data.map((category) => <Link className="category-card" to={`/cars?category_id=${category.id}`} key={category.id}><CarFront size={25} /><strong>{category.title}</strong><ArrowRight size={16} /></Link>)}</div>}</main> }

function Favorites() { const favorites = useFavorites(); if (!useAuth().user) return <AuthRequired title="Your saved cars" />; return <main className="page"><p className="eyebrow accent">Your garage</p><h1 className="page-title">Saved<br /><em>for later.</em></h1>{favorites.error ? <ErrorState error={favorites.error} /> : !favorites.favorites.length ? <Empty title="No favorites yet" text="Save cars you want to come back to." /> : <div className="car-grid">{favorites.favorites.map((car) => <CarCard key={car.id} car={car} favoriteIds={favorites.ids} onFavorite={favorites.toggle} />)}</div>}</main> }

function Compare() { const { ids } = useCompare(); const [cars, setCars] = useState([]); useEffect(() => { Promise.all(ids.map((id) => api.get(`/product/${id}/`))).then((responses) => setCars(responses.map((response) => response.data.product))).catch(() => setCars([])) }, [ids]); if (!ids.length) return <main className="page"><Empty title="Nothing to compare" text="Choose up to four cars from the inventory." /><Link className="primary-btn inline-btn" to="/cars">Browse cars <ArrowRight size={16} /></Link></main>; const fields = [['Price', (car) => `€${Number(car.price).toLocaleString()}`], ['Year', (car) => car.year], ['Mileage', (car) => `${Number(car.mileage).toLocaleString()} km`], ['Fuel', (car) => car.fuel_type], ['Transmission', (car) => car.transmission], ['Body type', (car) => car.body_type], ['Location', (car) => car.location]]; return <main className="page"><p className="eyebrow accent">Shortlist</p><h1 className="page-title">Compare<br /><em>what matters.</em></h1><div className="compare-table"><div className="compare-row compare-head"><span>Attribute</span>{cars.map((car) => <strong key={car.id}>{car.brand} {car.model_name}</strong>)}</div>{fields.map(([label, value]) => <div className="compare-row" key={label}><span>{label}</span>{cars.map((car) => <strong key={car.id}>{value(car)}</strong>)}</div>)}</div></main> }

function Orders() { const { user } = useAuth(); const [orders, setOrders] = useState(null); const [form, setForm] = useState({ address: '', phone_number: '' }); const [error, setError] = useState(null); const [submitting, setSubmitting] = useState(false); const [created, setCreated] = useState(false); const load = () => api.get('/order/').then(({ data }) => setOrders(data)).catch(setError); useEffect(() => { if (user) load() }, [user]); if (!user) return <AuthRequired title="Your requests" />; const create = async (event) => { event.preventDefault(); setError(null); setCreated(false); setSubmitting(true); try { await api.post('/order/', form); setForm({ address: '', phone_number: '' }); setCreated(true); load() } catch (requestError) { setError(requestError) } finally { setSubmitting(false) } }; return <main className="page"><p className="eyebrow accent">Your requests</p><h1 className="page-title">Order<br /><em>history.</em></h1>{error && <ErrorState error={error} />}{created && <p className="success">Order created successfully. We will contact you shortly.</p>}{orders === null ? <Loading label="Loading requests" /> : !orders.length ? <Empty title="No orders yet" text="Add a car to your request from its detail page." /> : <div className="order-list">{orders.map((order) => <Link to={`/orders/${order.id}`} className="order-card" key={order.id}><span>#{String(order.id).slice(0, 8)}</span><strong>{order.status}</strong><small>{new Date(order.created_at).toLocaleDateString()}</small><ArrowRight size={16} /></Link>)}</div>}<form className="request-form" onSubmit={create}><h3>Submit your current request</h3><input value={form.address} onChange={(event) => setForm({ ...form, address: event.target.value })} placeholder="Preferred contact address" required /><input value={form.phone_number} onChange={(event) => setForm({ ...form, phone_number: event.target.value })} placeholder="Phone number" /><button className="primary-btn" disabled={submitting}>{submitting ? 'Creating order...' : 'Create order request'} <ArrowRight size={16} /></button></form></main> }

function OrderDetail() { const { id } = useParams(); const [state, setState] = useState(null); useEffect(() => { api.get(`/order/${id}/`).then(({ data }) => setState(data)).catch(() => setState(false)) }, [id]); if (state === null) return <main className="page"><Loading label="Loading order" /></main>; if (!state) return <main className="page"><Empty title="Order not found" text="This request is unavailable." /></main>; return <main className="page"><p className="eyebrow accent">Request #{String(state.id).slice(0, 8)}</p><h1 className="page-title">Order<br /><em>details.</em></h1><div className="order-detail"><strong>Status: {state.status}</strong><p>{state.address}</p>{state.items.map((item) => <div className="order-item" key={item.id}><span>{item.product}</span><strong>€{Number(item.total_price).toLocaleString()}</strong></div>)}</div></main> }

function Cart() {
  const { user } = useAuth(); const [cart, setCart] = useState(null); const [error, setError] = useState(null)
  const load = () => api.get('/card/').then(({ data }) => setCart(data)).catch(setError)
  useEffect(() => { if (user) load() }, [user])
  if (!user) return <AuthRequired title="Your cart" />
  if (error) return <main className="page"><ErrorState error={error} retry={load} /></main>
  if (!cart) return <main className="page"><Loading label="Loading cart" /></main>
  const total = cart.items.reduce((sum, item) => sum + Number(item.price) * item.count, 0)
  const update = async (item, count) => { try { await api.patch(`/card/items/${item.id}/`, { count }); load() } catch (requestError) { setError(requestError) } }
  return <main className="page"><p className="eyebrow accent">Your shortlist</p><h1 className="page-title">Ready<br /><em>when you are.</em></h1>{!cart.items.length ? <Empty title="Your cart is empty" text="Add a car from its detail page to start a request." /> : <div className="cart-list">{cart.items.map((item) => <div className="order-card" key={item.id}><Link to={`/cars/${item.product}`}><strong>{item.product_title}</strong></Link><span>€{Number(item.price).toLocaleString()}</span><input aria-label={`Quantity for ${item.product_title}`} type="number" min="1" value={item.count} onChange={(event) => update(item, Number(event.target.value))} /><button className="reset-button" onClick={() => api.delete(`/card/items/${item.id}/`).then(load).catch(setError)}><X size={15} />Remove</button></div>)}</div>}<div className="cart-total"><strong>Total</strong><strong>€{total.toLocaleString()}</strong></div>{cart.items.length > 0 && <Link className="primary-btn inline-btn" to="/orders">Continue to order <ArrowRight size={16} /></Link>}</main>
}

function AuthRequired({ title }) { return <main className="page simple-page"><CircleUserRound size={31} className="accent-icon" /><h1>{title}</h1><p>Sign in to keep your marketplace activity with you.</p><Link className="primary-btn inline-btn" to="/login">Sign in <ArrowRight size={16} /></Link></main> }
function Login() { const { login } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ user_input: '', password: '' }); const [error, setError] = useState(null); const [loading, setLoading] = useState(false); const submit = async (event) => { event.preventDefault(); setLoading(true); setError(null); try { await login(form); navigate('/') } catch (requestError) { setError(requestError) } finally { setLoading(false) } }; return <AuthForm title="Welcome back." submit={submit} error={error} loading={loading} fields={<><label>Email, phone or username<input value={form.user_input} onChange={(event) => setForm({ ...form, user_input: event.target.value })} autoComplete="username" required /></label><label>Password<input type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} autoComplete="current-password" required /></label></>} footer={<Link to="/register">New to Motive? Create an account</Link>} /> }
function Register() { const navigate = useNavigate(); const [form, setForm] = useState({ user_input: '', password: '', conf_password: '' }); const [error, setError] = useState(null); const [loading, setLoading] = useState(false); const submit = async (event) => { event.preventDefault(); setLoading(true); setError(null); try { const { data } = await api.post('/auth/signup', form); localStorage.setItem('access', data.access); localStorage.setItem('refresh', data.refresh); navigate('/verify') } catch (requestError) { setError(requestError) } finally { setLoading(false) } }; return <AuthForm title="Start with the right car." submit={submit} error={error} loading={loading} fields={<><label>Email or phone number<input value={form.user_input} onChange={(event) => setForm({ ...form, user_input: event.target.value })} autoComplete="email" required /></label><label>Password<input type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} minLength="8" required /></label><label>Confirm password<input type="password" value={form.conf_password} onChange={(event) => setForm({ ...form, conf_password: event.target.value })} required /></label></>} footer={<Link to="/login">Already have an account? Sign in</Link>} /> }
function Verify() { const navigate = useNavigate(); const [code, setCode] = useState(''); const [error, setError] = useState(null); const submit = async (event) => { event.preventDefault(); try { await api.post('/auth/code-verify', { code }); navigate('/profile/setup') } catch (requestError) { setError(requestError) } }; return <AuthForm title="Check your inbox." submit={submit} error={error} fields={<label>Verification code<input value={code} onChange={(event) => setCode(event.target.value)} inputMode="numeric" maxLength="4" required /></label>} footer={<small>Enter the code printed by the development server for this environment.</small>} /> }
function ProfileSetup() { const { setUser } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ first_name: '', last_name: '', username: '', password: '', conf_password: '' }); const [error, setError] = useState(null); const submit = async (event) => { event.preventDefault(); try { const { data } = await api.patch('/auth/change-info', form); if (data.token) { localStorage.setItem('access', data.token.access); localStorage.setItem('refresh', data.token.refresh) } const profile = await api.get('/auth/profile'); setUser(profile.data); navigate('/') } catch (requestError) { setError(requestError) } }; return <AuthForm title="Make it yours." submit={submit} error={error} fields={Object.keys(form).map((key) => <label key={key}>{key.replace('_', ' ')}<input type={key.includes('password') ? 'password' : 'text'} value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} required /></label>)} /> }
function AuthForm({ title, submit, fields, error, footer, loading }) { return <main className="page login-page"><div className="login-card"><p className="eyebrow accent">MOTIVE account</p><h1>{title}</h1><p>Keep your saved cars, comparisons, and requests in one place.</p><form onSubmit={submit}>{fields}{error && <p className="form-error">{message(error)}</p>}<button className="primary-btn" disabled={loading}>{loading ? 'Working...' : 'Continue'} <ArrowRight size={16} /></button></form>{footer && <small>{footer}</small>}</div></main> }

function Profile() { const { user, setUser } = useAuth(); const [form, setForm] = useState({ first_name: user?.first_name || '', last_name: user?.last_name || '', username: user?.username || '', password: '', conf_password: '' }); const [saved, setSaved] = useState(false); const [error, setError] = useState(null); if (!user) return <AuthRequired title="Your profile" />; const submit = async (event) => { event.preventDefault(); setError(null); try { const { data } = await api.patch('/auth/change-info', form); if (data.token) { localStorage.setItem('access', data.token.access); localStorage.setItem('refresh', data.token.refresh) } const profile = await api.get('/auth/profile'); setUser(profile.data); setSaved(true) } catch (requestError) { setError(requestError) } }; return <main className="page profile-page"><p className="eyebrow accent">Your account</p><h1 className="page-title">Profile<br /><em>details.</em></h1><form className="profile-form" onSubmit={submit}>{['first_name', 'last_name', 'username'].map((key) => <label key={key}>{key.replace('_', ' ')}<input value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} required /></label>)}<label>Email<input value={user.email || ''} disabled /></label><label>Phone<input value={user.phone_number || ''} disabled /></label><label>New password (optional)<input type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value, conf_password: event.target.value })} minLength="8" /></label><button className="primary-btn">Save profile <ArrowRight size={16} /></button>{error && <p className="form-error">{message(error)}</p>}{saved && <p className="success">Profile updated.</p>}</form></main> }

function AppShell() { const { loading } = useAuth(); if (loading) return <Loading label="Loading account" />; return <><Header /><Routes><Route path="/" element={<Home />} /><Route path="/cars" element={<Catalog />} /><Route path="/catalog" element={<Catalog />} /><Route path="/cars/:id" element={<Detail />} /><Route path="/car/:id" element={<Detail />} /><Route path="/categories" element={<Categories />} /><Route path="/favorites" element={<Favorites />} /><Route path="/compare" element={<Compare />} /><Route path="/cart" element={<Cart />} /><Route path="/orders" element={<Orders />} /><Route path="/orders/:id" element={<OrderDetail />} /><Route path="/login" element={<Login />} /><Route path="/register" element={<Register />} /><Route path="/verify" element={<Verify />} /><Route path="/profile/setup" element={<ProfileSetup />} /><Route path="/profile" element={<Profile />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes><nav className="mobile-nav"><Link to="/"><CarFront size={18} />Home</Link><Link to="/cars"><Search size={18} />Cars</Link><Link to="/favorites"><Heart size={18} />Favorites</Link><Link to="/cart"><SlidersHorizontal size={18} />Cart</Link><Link to="/profile"><UserRound size={18} />Profile</Link></nav></> }
export default function App() { return <BrowserRouter><AuthProvider><CompareProvider><AppShell /></CompareProvider></AuthProvider></BrowserRouter> }
